### PR TITLE
Release 2.5.6/5.0.6

### PR DESCRIPTION
**Pull request by Pure-AdamuKaapan**
Releases Flex plugin version 2.5.6 and CSI plugin version 5.0.6. Tested with manual validation.

### CODE REVIEW

**Comment by Pure-AdamuKaapan** [comment]
# 2.5.6/5.0.6 release validation
## Values for all tests
```yaml
flasharray:
  sanType: ISCSI

arrays:
  FlashArrays:
    # fs66-a
    - MgmtEndPoint: "10.19.66.136"
      APIToken: "eb9476a0-9f9e-0ca3-a3a6-a48d9a961850"
      Labels:
        rack: "22"
        env: "prod"
```

## Kubernetes 1.15
### Flex Helm Chart
```bash
# git status
On branch Release256-506
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        kube-15.conf
        kube-16.conf
        operator-csi-plugin/helm-charts/
        operator-k8s-plugin/helm-charts/
        values.yaml

nothing added to commit but untracked files present (use "git add" to track)

# kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.9", GitCommit:"2e808b7cb054ee242b68e62455323aa783991f03", GitTreeState:"clean", BuildDate:"2020-01-18T23:24:23Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

# helm install pure-flex pure-k8s-plugin -f values.yaml
coalesce.go:165: warning: skipped value for arrays: Not a table.
NAME: pure-flex
LAST DEPLOYED: Tue Feb  4 10:18:46 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None

# kubectl get pods --all-namespaces
NAMESPACE       NAME                                      READY     STATUS      RESTARTS   AGE
...
default         pure-flex-srnkr                           1/1       Running     0          3m54s
default         pure-provisioner-d54d5cc7b-wk97f          1/1       Running     0          3m54s
...

# helm del pure-flex
release "pure-flex" uninstalled
```

### Flex Operator
```bash
# git status
On branch Release256-506
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        ../kube-15.conf
        ../kube-16.conf
        ../operator-csi-plugin/helm-charts/
        helm-charts/
        ../values.yaml

nothing added to commit but untracked files present (use "git add" to track)

# kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.9", GitCommit:"2e808b7cb054ee242b68e62455323aa783991f03", GitTreeState:"clean", BuildDate:"2020-01-18T23:24:23Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

# ./install.sh -f ../values.yaml --orchestrator=k8s    
namespace/pso-operator created
customresourcedefinition.apiextensions.k8s.io/psoplugins.purestorage.com created
clusterrole.rbac.authorization.k8s.io/pso-operator created
clusterrolebinding.rbac.authorization.k8s.io/pso-operator-role created
role.rbac.authorization.k8s.io/pso-operator created
rolebinding.rbac.authorization.k8s.io/default-account-pso-operator created
deployment.extensions/pso-operator created
psoplugin.purestorage.com/psoplugin-operator created

# kubectl get pods --all-namespaces
NAMESPACE       NAME                                      READY     STATUS      RESTARTS   AGE
...
pso-operator    pso-operator-7b7d7c96c-drgn7              1/1       Running     0          21s
pso-operator    pure-flex-dvdps                           1/1       Running     0          10s
pso-operator    pure-provisioner-5dc4cb56f4-v9pm9         1/1       Running     0          10s

# kubectl delete PSOPlugin -n pso-operator psoplugin-operator
psoplugin.purestorage.com "psoplugin-operator" deleted

# kubectl delete all --all -n pso-operator
pod "pso-operator-7b7d7c96c-drgn7" deleted
deployment.apps "pso-operator" deleted
replicaset.apps "pso-operator-7b7d7c96c" deleted

# kubectl delete namespace pso-operator
namespace "pso-operator" deleted

# kubectl delete crd psoplugins.purestorage.com
customresourcedefinition.apiextensions.k8s.io "psoplugins.purestorage.com" deleted
```

### CSI Helm Chart
```bash
# git status 
On branch Release256-506
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        kube-15.conf
        kube-16.conf
        operator-csi-plugin/helm-charts/
        operator-k8s-plugin/helm-charts/
        values.yaml

nothing added to commit but untracked files present (use "git add" to track)

# kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.9", GitCommit:"2e808b7cb054ee242b68e62455323aa783991f03", GitTreeState:"clean", BuildDate:"2020-01-18T23:24:23Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

# helm install pure-csi pure-csi -f values.yaml
coalesce.go:165: warning: skipped value for arrays: Not a table.
NAME: pure-csi
LAST DEPLOYED: Tue Feb  4 10:32:59 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None

# kubectl get pods --all-namespaces
NAMESPACE       NAME                                      READY     STATUS      RESTARTS   AGE
...
default         pure-csi-wfpj2                            3/3       Running     0          3m39s
default         pure-provisioner-0                        3/3       Running     0          3m39s
...

# kubectl get CSIDriver
NAME       CREATED AT
pure-csi   2020-02-04T18:33:01Z

# helm del pure-csi
release "pure-csi" uninstalled
```

### CSI Operator
```bash
# git status
On branch Release256-506
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        ../kube-15.conf
        ../kube-16.conf
        helm-charts/
        ../operator-k8s-plugin/helm-charts/
        ../values.yaml

nothing added to commit but untracked files present (use "git add" to track)

# kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.9", GitCommit:"2e808b7cb054ee242b68e62455323aa783991f03", GitTreeState:"clean", BuildDate:"2020-01-18T23:24:23Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

# ./install.sh -f ../values.yaml --orchestrator=k8s
namespace/pure-csi-operator created
customresourcedefinition.apiextensions.k8s.io/psoplugins.purestorage.com created
clusterrole.rbac.authorization.k8s.io/pso-operator configured
clusterrolebinding.rbac.authorization.k8s.io/pso-operator-role configured
role.rbac.authorization.k8s.io/pso-operator created
rolebinding.rbac.authorization.k8s.io/default-account-pso-operator created
deployment.extensions/pso-operator created
psoplugin.purestorage.com/psoplugin-operator created
volumesnapshotclass.snapshot.storage.k8s.io/pure-snapshotclass created

# kubectl get pods --all-namespaces
NAMESPACE           NAME                                      READY     STATUS      RESTARTS   AGE
...
pure-csi-operator   pso-operator-697946fc65-ts94n             1/1       Running     0          61s
pure-csi-operator   pure-csi-xgnbt                            3/3       Running     0          54s
pure-csi-operator   pure-provisioner-0                        3/3       Running     0          54s

# kubectl get CSIDriver
NAME       CREATED AT
pure-csi   2020-02-04T18:39:04Z

# kubectl delete PSOPlugin -n pure-csi-operator psoplugin-operator
psoplugin.purestorage.com "psoplugin-operator" deleted

# kubectl delete all --all -n pure-csi-operator
pod "pso-operator-697946fc65-ts94n" deleted
deployment.apps "pso-operator" deleted
replicaset.apps "pso-operator-697946fc65" deleted

# kubectl delete namespace pure-csi-operator
namespace "pure-csi-operator" deleted

# kubectl delete crd psoplugins.purestorage.com
customresourcedefinition.apiextensions.k8s.io "psoplugins.purestorage.com" deleted
```

## Kubernetes 1.16
### Flex Helm Chart
```bash
# git status
On branch Release256-506
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        kube-15.conf
        kube-16.conf
        operator-csi-plugin/helm-charts/
        operator-k8s-plugin/helm-charts/
        values.yaml

nothing added to commit but untracked files present (use "git add" to track)

# kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:23:21Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

# helm install pure-flex pure-k8s-plugin -f values.yaml
coalesce.go:165: warning: skipped value for arrays: Not a table.
NAME: pure-flex
LAST DEPLOYED: Tue Feb  4 11:09:10 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None

# kubectl get pods --all-namespaces
NAMESPACE       NAME                                      READY     STATUS      RESTARTS   AGE
...
default         pure-flex-2dppr                           1/1       Running     0          17s
default         pure-provisioner-b5cf7cc98-k8xhn          1/1       Running     0          17s
...

# helm del pure-flex
release "pure-flex" uninstalled
```

### Flex Operator
```bash
# git status
On branch Release256-506
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        ../kube-15.conf
        ../kube-16.conf
        ../operator-csi-plugin/helm-charts/
        helm-charts/
        ../values.yaml

nothing added to commit but untracked files present (use "git add" to track)

# kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:23:21Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

# ./install.sh -f ../values.yaml --orchestrator=k8s
namespace/pso-operator created
customresourcedefinition.apiextensions.k8s.io/psoplugins.purestorage.com created
clusterrole.rbac.authorization.k8s.io/pso-operator created
clusterrolebinding.rbac.authorization.k8s.io/pso-operator-role created
role.rbac.authorization.k8s.io/pso-operator created
rolebinding.rbac.authorization.k8s.io/default-account-pso-operator created
deployment.apps/pso-operator created
psoplugin.purestorage.com/psoplugin-operator created

# kubectl get pods --all-namespaces
NAMESPACE       NAME                                      READY     STATUS      RESTARTS   AGE
...
pso-operator    pure-flex-2f74p                           1/1       Running     0          25s
pso-operator    pure-provisioner-6b9bc8984d-nv4sh         1/1       Running     0          25s

# kubectl delete PSOPlugin -n pso-operator psoplugin-operator
psoplugin.purestorage.com "psoplugin-operator" deleted (NOTE: I had to edit this manually to get it to delete, a finalizer was hung up)

# kubectl delete all --all -n pso-operator 
pod "pso-operator-68b8f6dffc-4tc8x" deleted
deployment.apps "pso-operator" deleted
replicaset.apps "pso-operator-68b8f6dffc" deleted

# kubectl delete namespace pso-operator
Error from server (NotFound): namespaces "pso-operator" not found (failed due to that edit earlier)
```

### CSI Helm Chart
```bash
# git status
On branch Release256-506
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        kube-15.conf
        kube-16.conf
        operator-csi-plugin/helm-charts/
        operator-k8s-plugin/helm-charts/
        values.yaml

nothing added to commit but untracked files present (use "git add" to track)

# kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:23:21Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

# helm install pure-csi pure-csi -f values.yaml
coalesce.go:165: warning: skipped value for arrays: Not a table.
NAME: pure-csi
LAST DEPLOYED: Tue Feb  4 11:18:36 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None

# kubectl get pods --all-namespaces
NAMESPACE       NAME                                      READY     STATUS      RESTARTS   AGE
...
default         pure-csi-2jtzr                            3/3       Running     0          53s
default         pure-provisioner-0                        3/3       Running     0          53s
...

# kubectl get CSIDriver
NAME       CREATED AT
pure-csi   2020-02-04T19:18:37Z

# helm del pure-csi
release "pure-csi" uninstalled
```

### CSI Operator
```bash
# git status
On branch Release256-506
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        ../kube-15.conf
        ../kube-16.conf
        helm-charts/
        ../operator-k8s-plugin/helm-charts/
        ../values.yaml

nothing added to commit but untracked files present (use "git add" to track)

# kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:23:21Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

# ./install.sh -f ../values.yaml --orchestrator=k8s
namespace/pure-csi-operator created
customresourcedefinition.apiextensions.k8s.io/psoplugins.purestorage.com configured
clusterrole.rbac.authorization.k8s.io/pso-operator configured
clusterrolebinding.rbac.authorization.k8s.io/pso-operator-role configured
role.rbac.authorization.k8s.io/pso-operator created
rolebinding.rbac.authorization.k8s.io/default-account-pso-operator created
deployment.apps/pso-operator created
psoplugin.purestorage.com/psoplugin-operator created
volumesnapshotclass.snapshot.storage.k8s.io/pure-snapshotclass created

# kubectl get pods --all-namespaces
NAMESPACE           NAME                                      READY     STATUS      RESTARTS   AGE
...
pure-csi-operator   pure-csi-5jthk                            3/3       Running     0          55s
pure-csi-operator   pure-provisioner-0                        3/3       Running     0          55s

# kubectl get CSIDriver
NAME       CREATED AT
pure-csi   2020-02-04T19:20:53Z

# kubectl delete PSOPlugin -n pure-csi-operator psoplugin-operator
psoplugin.purestorage.com "psoplugin-operator" deleted (NOTE: had to manually edit this as well to get it to delete, a stuck finalizer again)

# kubectl delete all --all -n pure-csi-operator
pod "pso-operator-6bcd56d5c5-dm5j4" deleted
deployment.apps "pso-operator" deleted
replicaset.apps "pso-operator-6bcd56d5c5" deleted

# kubectl delete namespace pure-csi-operator
namespace "pure-csi-operator" deleted
```

**Comment by sdodsley** [comment]
Any change we can validate against 1.17 as well, given that is GA.
1.18 is close to release as well. I know this is incrementing fast, but we need to keep on top of this.

**Comment by Pure-AdamuKaapan** [comment]
@sdodsley I'll run a test on 1.17 right now. We'll have to figure out a better way to test 1.18 in the future (or prereleases/betas in general)

**Comment by Pure-AdamuKaapan** [comment]
@sdodsley I've confirmed it works on 1.17.

## Kubernetes 1.17
### Flex Helm Chart
```bash
# git status
On branch Release256-506
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        kube-15.conf
        kube-16.conf
        kube-17.conf
        operator-csi-plugin/helm-charts/
        operator-k8s-plugin/helm-charts/
        values.yaml

nothing added to commit but untracked files present (use "git add" to track)

# kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

# helm install pure-flex pure-k8s-plugin -f values.yaml
coalesce.go:165: warning: skipped value for arrays: Not a table.
NAME: pure-flex
LAST DEPLOYED: Tue Feb  4 12:04:13 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None

# kubectl get pods --all-namespaces
NAMESPACE       NAME                                      READY     STATUS      RESTARTS   AGE
...
default         pure-flex-2n2tw                           1/1       Running     0          15s
default         pure-provisioner-b5cf7cc98-xnbl9          1/1       Running     0          15s
...

# helm del pure-flex
release "pure-flex" uninstalled
```

### Flex Operator
```bash
# git status
On branch Release256-506
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        ../example.yaml
        ../kube-15.conf
        ../kube-16.conf
        ../kube-17.conf
        ../operator-csi-plugin/helm-charts/
        helm-charts/
        ../values.yaml

nothing added to commit but untracked files present (use "git add" to track)

# kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

# ./install.sh -f ../values.yaml --orchestrator=k8s
namespace/pso-operator created
customresourcedefinition.apiextensions.k8s.io/psoplugins.purestorage.com created
clusterrole.rbac.authorization.k8s.io/pso-operator created
clusterrolebinding.rbac.authorization.k8s.io/pso-operator-role created
role.rbac.authorization.k8s.io/pso-operator created
rolebinding.rbac.authorization.k8s.io/default-account-pso-operator created
deployment.apps/pso-operator created
psoplugin.purestorage.com/psoplugin-operator created

# kubectl get pods --all-namespaces
NAMESPACE       NAME                                      READY     STATUS      RESTARTS   AGE
...
pso-operator    pso-operator-68b8f6dffc-kdd24             1/1       Running     0          17s
pso-operator    pure-flex-qkx7v                           1/1       Running     0          4s
pso-operator    pure-provisioner-6b9bc8984d-f85jg         1/1       Running     0          4s

# kubectl delete PSOPlugin -n pso-operator psoplugin-operator
psoplugin.purestorage.com "psoplugin-operator" deleted (NOTE: had to edit finalizer again)

# kubectl delete all --all -n pso-operator
pod "pso-operator-68b8f6dffc-kdd24" deleted
deployment.apps "pso-operator" deleted
replicaset.apps "pso-operator-68b8f6dffc" deleted

# kubectl delete namespace pso-operator
namespace "pso-operator" deleted
```

### CSI Helm Chart
```bash
# git status
On branch Release256-506
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        example.yaml
        kube-15.conf
        kube-16.conf
        kube-17.conf
        operator-csi-plugin/helm-charts/
        operator-k8s-plugin/helm-charts/
        values.yaml

nothing added to commit but untracked files present (use "git add" to track)

# kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

# helm install pure-csi pure-csi -f values.yaml
coalesce.go:165: warning: skipped value for arrays: Not a table.
NAME: pure-csi
LAST DEPLOYED: Tue Feb  4 12:10:22 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None

# kubectl get pods --all-namespaces
NAMESPACE       NAME                                      READY     STATUS      RESTARTS   AGE
...
default         pure-csi-6fj78                            3/3       Running     0          26s
default         pure-provisioner-0                        3/3       Running     0          26s
...

# kubectl get CSIDriver
NAME       CREATED AT
pure-csi   2020-02-04T20:10:23Z

# helm del pure-csi
release "pure-csi" uninstalled
```

### CSI Operator
```bash
# git status
On branch Release256-506
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        ../example.yaml
        ../kube-15.conf
        ../kube-16.conf
        ../kube-17.conf
        helm-charts/
        ../operator-k8s-plugin/helm-charts/
        ../values.yaml

nothing added to commit but untracked files present (use "git add" to track)

# kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

# ./install.sh -f ../values.yaml --orchestrator=k8s
namespace/pure-csi-operator created
customresourcedefinition.apiextensions.k8s.io/psoplugins.purestorage.com configured
clusterrole.rbac.authorization.k8s.io/pso-operator configured
clusterrolebinding.rbac.authorization.k8s.io/pso-operator-role configured
role.rbac.authorization.k8s.io/pso-operator created
rolebinding.rbac.authorization.k8s.io/default-account-pso-operator created
deployment.apps/pso-operator created
psoplugin.purestorage.com/psoplugin-operator created
volumesnapshotclass.snapshot.storage.k8s.io/pure-snapshotclass created

# kubectl get pods --all-namespaces
NAMESPACE           NAME                                      READY     STATUS      RESTARTS   AGE
...
pure-csi-operator   pso-operator-6bcd56d5c5-blbsw             1/1       Running     0          16s
pure-csi-operator   pure-csi-xq7z2                            3/3       Running     0          10s
pure-csi-operator   pure-provisioner-0                        3/3       Running     0          10s

# kubectl get CSIDriver
NAME       CREATED AT
pure-csi   2020-02-04T20:12:08Z

# kubectl delete PSOPlugin -n pure-csi-operator psoplugin-operator
psoplugin.purestorage.com "psoplugin-operator" deleted (NOTE: still had to delete the finalizer manually)

# kubectl delete all --all -n pure-csi-operator
pod "pso-operator-6bcd56d5c5-blbsw" deleted
deployment.apps "pso-operator" deleted
replicaset.apps "pso-operator-6bcd56d5c5" deleted

# kubectl delete namespace pure-csi-operator
namespace "pure-csi-operator" deleted
```

**Pull request merged**
