### PR TITLE
allow csi images to be customisable

### PR DESCRIPTION
**Pull request by javefang**
allow all quay.io/k8scsi/* images to be customisable. necessary for those k8s clusters that don't have access to public docker registries.

(I haven't updated `Chart.yaml` and hasn't run`update.sh` yet. Could someone advise where can I find the doc for the release process, please?)

### CODE REVIEW

**Comment by pure-yesmat** [comment]
Interesting.

I understand the need to change the location of the images, but changing the tag could be problematic because our driver could depend on features in a specific version/tag.

Perhaps we should just have a customizable registry, ie prefix to the image name and tag. Something like:

```yaml
image: "{{.Values.image.registry}}k8scsi/csi-provisioner:v1.1.0"
```

**Comment by javefang** [comment]
Hi @pure-yesmat , it's quite common in helm charts where image could be customised. Your concern about tag does make sense, however I'm not exactly sure how other users are going to tag their image so it's probably better to leave it fully customisable.

Since image name and tag are already separated and have reasonable default set, there is very little chance anyone could break it while overriding the image name. The only way they can break it is when then override the tag, which they have been warned.

**Comment by pure-yesmat** [comment]
sorry for the delay @javefang, i'll get back to you by the EOD.

**Comment by pure-yesmat** [comment]
Hi @javefang,

I think we are ok with having a customizable name but not tag. So we can have it something like:
```yaml
image: "{{.Values.image.name}}:v1.1.0"
```

**Comment by javefang** [comment]
Hi @pure-yesmat, I have udpated my PR to disallow csi image tags to be customised.

**Comment by Pure-AdamuKaapan** [comment]
Tested locally and seems to apply values as expected (mainly by setting them to purposefully wrong values and verifying that they crash as expected, since I don't have those images pushed to a repo of our own and figured this was a faster test).

**Pull request merged**
