### PR TITLE
Store pure config as Secret

### PR DESCRIPTION
**Pull request by javefang**
The .Values.array currently contains the api tokens, which ideally should be stored as Secret.

### CODE REVIEW

**Comment by javefang** [comment]
Solves https://github.com/purestorage/helm-charts/issues/72

**Comment by taherv** [comment]
this is a change with a large impact,
cc @dinathom @patrick-east @pure-yesmat @trevormeiss

**Comment by javefang** [comment]
@taherv a helm upgrade should handle the change transparently for user though (delete configmap and create secret). but yes you may want to take a better look.

**Comment by javefang** [comment]
The main reason I'm raising this is because our policy doesn't allow api tokens to be stored in ConfigMap (for a good reason I think).

**Comment by javefang** [comment]
Thanks for reviewing! I will wait for https://github.com/purestorage/helm-charts/pull/73 to merge first, rebase on master and build a tarball for this. @pure-yesmat what should the new version number be?

**Comment by javefang** [comment]
Rebased on the latest master, bumped version and built tarball

**Comment by javefang** [comment]
@pure-yesmat @taherv when you have a chance could either of you take a look at this PR, please? much appreciated :)

**Comment by pure-yesmat** [comment]
Hi @javefang,

We will run the PR through some of our tests and if they pass we ill merge the PR.

**Comment by pure-yesmat** [comment]
Can you update pure-flex-daemon.yaml to use the secret instead of the config map as well.

**Comment by javefang** [comment]
Ah sorry I missed that one, good spot! Fixed and rebuilt tarball now :)

**Comment by javefang** [comment]
@taherv @pure-yesmat can we take another look after the fix , pls? thanks

**Comment by javefang** [comment]
Any news guys? :)

**Comment by dinathom** [comment]
We should not be bumping the version and build the tarball in Pull-requests. That is part of the release process.

**Pull request merged**
