### PR TITLE
Update docs to add EKS support

### PR DESCRIPTION
**Pull request by sdodsley**
Add AWS EKS 1.14 support for the CSI driver - both through operator and helm install methods

### CODE REVIEW

**Comment by trevormeiss** [comment]
Looks like EKS requires some initial setup of iscsi and multipath. Should we also add documentation on how to do this setup?

**Comment by sdodsley** [comment]
Yes. I will put something together about that in a separate document. This is just to add it to the supported list

**Comment by dsupure** [comment]
Should we add the scripts to help users to set up the iscai and multipath for EKS? We Have some handy scripts in the nsm-dev-tools.

**Comment by sdodsley** [comment]
That might be a really helpful option. We can reference them in the readme and create an EKS help directory in this repo as part of the PR to add the docs

**Pull request merged**
