### PR TITLE
Dinathom/nodeselect

### PR DESCRIPTION
**Pull request by dinathom**
Remove hard-coded nodeSelector from pure-flex template. 
By default our pure-flex will not have a nodeSelector specified which means we will default to using whatever is in the project-wide nodeSelector. If project-wide node selector is not specified it will use the cluster-wide node selector. See https://docs.openshift.com/container-platform/3.11/admin_guide/managing_projects.html#using-node-selectors

### CODE REVIEW

**Comment by sdodsley** [comment]
Have you confirmed that removing this will pick up the defaultNodeSelector setting?

**Comment by dinathom** [comment]
@sdodsley tested on Openshift 3.11 
1. in pso-namespace + no annotations on namespace. Daemonset pods get scheduled on all nodes labeled compute=true even as new compute nodes are added. 
2. If namespace has annotation openshift.io/node-selector: "" then daemonset pods are scheduled on all nodes irrespective of defaultNodeSelector in master-conf.yaml

**Comment by sdodsley** [comment]
@dinathom what happens with no annotations on pso namespace and you change {{defaultNodeSelector}} to be {{compute}} and {{master}}, then install PSO? Does it deploy pods on compute and master nodes?

**Comment by dinathom** [comment]
@sdodsley I have not found a 'set union' syntax with nodeSelector. According to the k8s manual nodeSelector is just a set of  key=value labels and multiple labels will mean -intersection of the labels. So I do not know how you would specify 'compute-and-master' in the master-config.yaml 
One way is to create a new label and apply it to both compute and master nodes.

**Comment by sdodsley** [comment]
@dinathom I'm struggling to find where I saw it. I agree that nodeSelector is a KVP map so you can't have two keys the same. I think what I may have read is that OpenShift don't mind if you use master for user pods now. 
This is all so confusing :) 
I still think we should go with the {{defaultNodeSelector}} value and insist in our documentation that the PSO installation uses its own project and not default.
I will ensure this is covered in the OpenShift 3.11 Ref Arch I'm writing.

**Pull request merged**
